import { localizedCopy } from '@/shared/i18n';

const rawMessengerCopy = {
  presence: {
    statusLabel: {
      dnd: "Không làm phiền",
      online: "Đang hoạt động",
      offline: "Ngoại tuyến",
      onlineSuffix: "đang hoạt động",
      offlineSuffix: "ngoại tuyến",
    },
    statusSelector: {
      onlineLabel: "Trực tuyến",
      onlineDescription: "Mọi người thấy bạn đang hoạt động",
      dndLabel: "Không làm phiền",
      dndDescription: "Tắt thông báo, hiển thị biểu tượng đỏ",
      invisibleLabel: "Vô hình",
      invisibleDescription: "Mọi người thấy bạn đang ngoại tuyến",
      title: "Trạng thái hoạt động",
      updateLoading: "Đang cập nhật...",
    },
    statusDot: {
      online: "Đang hoạt động",
      offline: "Ngoại tuyến",
    },
    tooltip: {
      conversationDefault: "Đang hoạt động",
      blocked: "Tin nhắn đã bị chặn",
      noMessage: "Chưa có tin nhắn",
    },
    list: {
      pin: "Ghim cuộc trò chuyện",
      unpin: "Bỏ ghim cuộc trò chuyện",
      searchNoResult: "Không có kết quả",
      searchRetryHint: "Nhập username khác để thử lại.",
      searchHintMinChars: "Nhập tối thiểu 2 ký tự để tìm người dùng.",
      creatingConversation: "Đang tạo...",
      startConversation: "Bắt đầu trò chuyện",
      connectUser: "Kết nối mới",
      modalHint: "Tìm bạn và bắt đầu trò chuyện",
      modalCloseAria: "Đóng modal",
      removeUserChipAria: "Bỏ chọn",
      userSearchPlaceholder: "Nhập username để tìm...",
      createRoomModalStep1Title: "Tạo phòng mới",
    },
    deviceSeparator: " • ",
  },
  conversationPreview: {
    emptyMessage: "Chưa có tin nhắn",
    updatedNotification: "Đã có cập nhật",
    joined: "Đã tham gia",
    left: "Đã rời phòng",
    promoted: "Đã thăng phó phòng",
    membershipUpdated: "Đã thay đổi thành viên",
    pinned: "Đã ghim tin nhắn",
    unpinned: "Đã bỏ ghim tin nhắn",
    poll: "Đã bình chọn",
    pollCreated: "Đã tạo bình chọn",
    pollVoted: "Đã bình chọn",
    attachment: "Đã đính kèm file",
    imageMessage: "đã gửi ảnh",
    fileMessage: "đã gửi tệp đính kèm",
    fileMessageWithName: "đã gửi tệp: ",
    emptyTextMessage: "Tin nhắn mới",
  },
  conversationItem: {
    presence: {
      dnd: "Không làm phiền",
      online: "Đang hoạt động",
      offline: "Ngoại tuyến",
      blockedMessage: "Tin nhắn đã bị chặn",
      noMessage: "Chưa có tin nhắn",
      tooltipUnpin: "Bỏ ghim cuộc trò chuyện",
      tooltipPin: "Ghim cuộc trò chuyện",
      presenceTitleTemplate: {
        online: "{{status}}",
        withDevice: "{{status}} • {{device}}",
        offlineWithAgo: "{{status}} • {{lastActiveAgo}}",
      },
    },
  },
  sidebar: {
    title: "Hội thoại",
    header: {
      contactsAriaLabel: "Mở danh bạ và lời mời",
      createRoomAriaLabel: "Tạo phòng mới",
      settingsAriaLabel: "Mở cài đặt",
      contactsTitle: "Danh sách bạn bè",
      createRoomTitle: "Tạo phòng mới",
      settingsTitle: "Cài đặt",
    },
    search: {
      placeholder: "Tìm kiếm cuộc trò chuyện",
    },
    emptyTitleWithFilter: "Không tìm thấy cuộc trò chuyện",
    emptyTitleDefault: "Chưa có cuộc trò chuyện",
    emptyHintWithFilter: "Thử lại với từ khóa khác hoặc kiểm tra bộ lọc ở phía trên.",
    emptyHintDefault: "Tạo phòng mới hoặc tìm bạn để bắt đầu trò chuyện.",
    footer: {
      contactsAriaLabel: "Danh sách bạn bè",
      settingsAriaLabel: "Mở cài đặt",
    },
  },
  conversationInfo: {
    title: "Thông tin",
    notificationTitle: "Thông báo phòng",
    notificationDescription: "Chọn mức thông báo mặc định của phòng và thiết lập riêng cho bạn.",
    roomNotificationLabel: "Mặc định của phòng",
    memberNotificationLabel: "Cài đặt của bạn",
    inheritedNotificationLabel: "Theo mặc định phòng",
    inheritedNotificationHint: "Dùng mức thông báo do phòng đặt.",
    ownerNotificationHint: "Chủ phòng có thể thay đổi mức mặc định cho tất cả thành viên.",
    memberNotificationHint: "Chỉ chủ phòng có thể thay đổi mức mặc định.",
    retryNotificationPolicy: "Thử lại",
    saveNotificationPolicy: "Lưu cài đặt thông báo",
    notificationPolicyLoadError: "Không thể tải cài đặt thông báo của phòng.",
    notificationPolicySaveError: "Không thể cập nhật cài đặt thông báo của phòng.",
    notificationPolicySaved: "Đã cập nhật cài đặt thông báo của phòng.",
    dangerZone: "Vùng nguy hiểm",
    unblockUser: "Bỏ chặn người dùng",
    blockUser: "Chặn người dùng",
    confirmBlock: "Bạn có chắc chắn muốn chặn người dùng này?",
  },
  messageHistory: {
    loadMore: "Tải thêm tin nhắn cũ",
  },
  mentionMenu: {
    title: "Nhắc đến",
    noMembers: "Không tìm thấy thành viên",
    allMembersLabel: "Mọi người",
    allMembersHint: "Thông báo tất cả thành viên",
  },
  errors: {
    loadConversationsFailed: "Không thể tải danh sách hội thoại.",
    loadMessagesFailed: "Không thể tải tin nhắn.",
    sendMessageFailed: "Không thể gửi tin nhắn.",
  },
    messageInput: {
    placeholder: "Viết tin nhắn của bạn... (gõ @ để nhắc tên)",
    toolbar: {
      attachFile: "Đính kèm file",
      attachMedia: "Đính kèm ảnh / video",
      createPoll: "Tạo bình chọn",
      pickEmoji: "Chọn emoji",
      callVoice: "Gọi thoại",
      searchEmoji: "Tìm emoji...",
    },
    actionSuccess: {
      copyPollCreated: "Đã tạo bình chọn.",
      copyPollCreateError: "Lỗi khi tạo bình chọn.",
      editSuccess: "Đã cập nhật tin nhắn.",
      sendSuccess: "Đã gửi tin nhắn.",
      sendFailure: "Gửi tin nhắn thất bại.",
      noValidFileToSend: "Không có file hợp lệ để gửi.",
      uploadFailed: "Upload file thất bại. Vui lòng thử lại.",
      uploadShortage: (count: number) => `Upload thiếu ${count} file.`,
      maxFilesPerMessage: 'Mỗi tin nhắn chỉ cho phép tối đa 10 file.',
      fileExtraAllowed: (slots: number) => `Chỉ chấp nhận thêm ${slots} file cho lượt gửi này.`,
    },
    actionError: {
      fileInvalid: (fileName: string) => `File "${fileName}" không hợp lệ.`,
      fileTooLarge: (fileName: string) => `File "${fileName}" vượt quá 10MB.`,
      fileUnsupportedType: (fileName: string) => `File "${fileName}" không đúng định dạng này.`,
      noConversationToSend: "Vui lòng chọn cuộc trò chuyện để gửi.",
      attachmentDisabledDuringEdit: () =>
        "Gửi file không được áp dụng khi chỉnh sửa tin nhắn.",
    },
    draftPanel: {
      replyLabel: "Đang trả lời",
      editLabel: "Đang chỉnh sửa",
    },
  },
  messageInputBlocked: {
    blockedByMe: "Bạn đã chặn người dùng này.",
    unblockAction: "Bỏ chặn",
    blockedByOther: "Bạn không thể gửi tin nhắn cho người này.",
  },
  typingIndicator: {
    userTyping: "{name} đang nhập...",
    othersTyping: "{count} người đang nhập...",
  },
  message: {
    hidden: "Tin nhắn đã bị ẩn",
    revealAction: "Xem",
    historyLabel: "Đã sửa",
    editedLabel: "Đã sửa",
    seenLabel: "Đã xem",
    sending: "Đang gửi...",
    failed: "Không gửi được",
    sent: "Đã gửi",
    retryTitle: "Thử gửi lại",
    replyLabel: "Trả lời",
    copyLabel: "Sao chép",
    pinLabel: "Ghim",
    editLabel: "Sửa",
    deleteLabel: "Xóa tin nhắn",
  },
  messageStatus: {
    deleted: "Tin nhắn đã bị xóa",
  },
  chatWindow: {
    status: {
      dnd: "Không làm phiền",
      online: "Đang hoạt động",
      offline: "Ngoại tuyến",
      groupMemberSuffix: "thành viên",
    },
    messageAction: {
      copySuccess: "Đã sao chép tin nhắn.",
      deleteSuccess: "Tin nhắn đã được xóa.",
      pinSuccess: "Cập nhật trạng thái ghim.",
      actionFailed: "Không thể hoàn tất thao tác với tin nhắn.",
      seenAt: (timestamp: string) => `Đã xem lúc ${timestamp}`,
      noReplyTarget: "Không có tin nhắn reply.",
      noMessageFoundInHistory: "Không tìm thấy tin nhắn trong lịch sử đã tải.",
    },
    placeholder: {
      emptyTitle: "Chọn một cuộc trò chuyện",
      emptyMessage: "Bắt đầu kết nối với bạn bè của bạn trong không gian trò chuyện mới.",
    },
    header: {
      goBackLabel: "Quay lại danh sách",
      searchTooltip: "Tìm trong cuộc trò chuyện",
      themeTooltip: "Thiết lập chủ đề phòng",
      themeInfo: "Mở/đóng thông tin phòng",
      themeInfoClosed: "Mở thông tin cuộc trò chuyện",
      voiceTooltip: "Gọi thoại",
      videoTooltip: "Gọi video",
    },
  },
  search: {
    messageFilter: {
      emptyMessage: "Không có kết quả phù hợp.",
      senderIdPlaceholder: "UUID người gửi",
      mentionedUserPlaceholder: "UUID người được nhắc",
      replyToSenderIdPlaceholder: "UUID người gửi trong tin nhắn reply",
      typeLabel: "Loại",
      messageTypeOptions: [
        { value: "", label: "Tất cả" },
        { value: "TEXT", label: "TEXT" },
        { value: "IMAGE", label: "IMAGE" },
        { value: "FILE", label: "FILE" },
        { value: "AUDIO", label: "AUDIO" },
        { value: "VIDEO", label: "VIDEO" },
        { value: "STICKER", label: "STICKER" },
        { value: "POLL", label: "POLL" },
        { value: "SYSTEM", label: "SYSTEM" },
      ],
      attachmentLabel: "Tệp đính kèm",
      attachmentOptions: [
        { value: "all", label: "Tất cả" },
        { value: "true", label: "Có tệp đính kèm" },
        { value: "false", label: "Không có tệp đính kèm" },
      ],
      pinnedLabel: "Trạng thái ghim",
      pinnedOptions: [
        { value: "all", label: "Tất cả" },
        { value: "true", label: "Đã ghim" },
        { value: "false", label: "Chưa ghim" },
      ],
      fromLabel: "Từ ngày",
      toLabel: "Đến ngày",
      clearLabel: "Xóa bộ lọc",
      loadMoreLabel: "Tải thêm kết quả",
      loadingMoreLabel: "Đang tải thêm kết quả...",
      loadMoreError: "Không thể tải thêm kết quả tìm kiếm. Vui lòng thử lại.",
      disabledHint:
        "Vui lòng mở một cuộc trò chuyện để dùng tìm kiếm nâng cao tin nhắn.",
    },
  },
  createRoomModal: {
    title: "Tạo phòng mới",
    stepOneTitle: "Thiết lập",
    stepTwoTitle: "Thành viên",
    roomNameLabel: "Tên phòng chat",
    roomNamePlaceholder: "VD: Team Frontend, Coffee Group...",
    roomDescriptionLabel: "Mô tả (Không bắt buộc)",
    roomDescriptionPlaceholder: "Phòng này dùng để làm gì?",
    roomTypeLabel: "Loại hình",
    roomTypeGroup: "Nhóm Chat",
    roomTypeGroupHint: "Riêng tư, bảo mật",
    roomTypeChannel: "Kênh (Channel)",
    roomTypeChannelHint: "Công khai, thông báo",
    membersEmpty: "Chưa chọn thành viên nào",
    searchPlaceholder: "Tìm kiếm bạn bè theo tên đăng nhập...",
    backButton: "Quay lại",
    nextButton: "Tiếp theo",
    createButtonLoading: "Đang tạo phòng...",
    createButton: "Tạo phòng ngay",
  },
  newConversationModal: {
    closeAriaLabel: "Đóng modal",
    removeChipAriaPrefix: "Bỏ chọn",
  },
} as const;

export const MESSENGER_COPY = localizedCopy(rawMessengerCopy);
